sudo: required
language: generic
dist: trusty
addons:
  apt:
    packages:
    - squashfs-tools
    - desktop-file-utils

services:
  - docker

before_install:
- wget --no-check-certificate https://raw.githubusercontent.com/gntech/mlt-scripts/Travis-build/docker/shotcut-build/Dockerfile
- mkdir shotcut-build
- mv Dockerfile shotcut-build/
- docker build --rm -t ddennedy/shotcut-build shotcut-build
- mkdir work; cd work
- wget --no-check-certificate https://raw.githubusercontent.com/mltframework/shotcut/master/scripts/build-shotcut.sh
- wget --no-check-certificate https://raw.githubusercontent.com/mltframework/shotcut/master/scripts/shotcut.nsi
- wget --no-check-certificate https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage

script:
- docker run -it --rm -v $PWD:/root/shotcut ddennedy/shotcut-build
- bash -ex pkg2appimage ../scripts/shotcut-recipe.yml

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "out/*.appimage"
  skip_cleanup: true
  on:
    branch: master
    tags: true

