sudo: required

language: cpp

services:
  - docker
  
before_install:
- wget --no-check-certificate https://raw.githubusercontent.com/gntech/mlt-scripts/Travis-build/docker/shotcut-build/Dockerfile
- mkdir shotcut-build
- mv Dockerfile shotcut-build/
- docker build --rm -t ddennedy/shotcut-build shotcut-build
- mkdir work; cd work
- wget --no-check-certificate https://raw.githubusercontent.com/gntech/shotcut/master/scripts/build-shotcut.sh
- wget --no-check-certificate https://raw.githubusercontent.com/mltframework/shotcut/master/scripts/shotcut.nsi
# Build snap and publish
- wget --no-check-certificate https://raw.githubusercontent.com/gntech/shotcut/master/scripts/build-and-publish-snap.sh

script:
- docker run -it --rm -v $PWD:/root/shotcut ddennedy/shotcut-build

deploy:
  skip_cleanup: true
  on:
    branch: master
    tags: true
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "shotcut.tar.bz2"
- provider: script
  script: build-and-publish-snap.sh
  # docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft sh -c "apt update && snapcraft && snapcraft push *.snap --release edge"
