sudo: required

language: cpp

services:
  - docker

branches:
  only:
  - build-with-travis
  
before_install:
- wget --no-check-certificate https://raw.githubusercontent.com/gntech/mlt-scripts/Travis-build/docker/shotcut-build/Dockerfile
- mkdir shotcut-build
- mv Dockerfile shotcut-build/
- docker build --rm -t ddennedy/shotcut-build shotcut-build
- mkdir work; cd work
- wget --no-check-certificate https://raw.githubusercontent.com/mltframework/shotcut/master/scripts/build-shotcut.sh
- wget --no-check-certificate https://raw.githubusercontent.com/mltframework/shotcut/master/scripts/shotcut.nsi

script:
- docker run -it --rm -v $PWD:/root/shotcut ddennedy/shotcut-build

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "$PWD:/root/shotcut/shotcut.tar.bz2"
  skip_cleanup: true

